version: "3.7"

services:
  app:
    build: .
    working_dir: /app
    init: true
    volumes:
      - .:/app
      - pkg:/go/pkg
    command: ["go", "run", "main.go", "./paths.csv"]

volumes:
  pkg:
